INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Armador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Eletricista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Encanador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Gesseiro');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Montador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante de Serralheria');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Ajudante Geral');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Almoxarife');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Apontador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Armador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Auxiliar de Eletricista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Auxiliar de Engenharia');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Auxiliar de Laboratório');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Azulegista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Bombeiro Hidráulico');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Carpinteiro');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Contramestre');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Coordenador(a) de Obras');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Diretor(a)');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Duteiro');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Eletricista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encanador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encarregado');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encarregado de Armador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encarregado de Elétrica');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encarregado de Hidráulica');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Encarregado de Pintura');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Engenheiro Seg. do Trabalho');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Engenheiro(a) Civil');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Engenheiro(a) Eletricista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Estagiário(a)');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Gerente de Projetos');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Impermeabilizador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Instalador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Laboratorista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Meio Oficial');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Mestre de Obras');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Montador');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Motorista');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Motorista de Caminhão');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Bomba de Concreto');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Caminhão Betoneira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Caminhão Munk');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Caminhão Perfuratriz');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Elevador Cremalheira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Empilhadeira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Grua / Mini Grua');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Pá Carregadeira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador de Perfuratriz');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador Mini Retroescavadeira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador Mini-carregadeira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Operador Retroescavadeira');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Pedreiro');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Pintor');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Secretária');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Serralheiro');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Servente');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Supervisor');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Técnico em Telecomunicações');
INSERT INTO funcoes (id, nome) VALUES (gen_random_uuid(),'Topógrafo');